#ifndef DEFAULT_WINDOW_CONFIG_H
#define DEFAULT_WINDOW_CONFIG_H

#define MY_GL_MAJOR_VERSION 4
#define MY_GL_MINOR_VERSION 3
#define GLSL_VERSION_STR "#version 330 core"

#define WINDOW_DEFAULT_WIDTH  800
#define WINDOW_DEFAULT_HEIGHT 600 
#define WINDOW_DEFAULT_TITLE "Application"


#endif // DEFAULT_WINDOW_CONFIG_H
